#ifndef COLORDATA_H_
#define COLORDATA_H_

#include <ncurses.h>

#define FREDBBLACK		1
#define FGREENBBLACK	2
#define FYELLOWBBLACK	3
#define FBLUEBBLACK		4
#define FMAGENTABBLACK	5
#define FCYANBBLACK		6
#define FWHITEBBLACK	7

//init_pair(FREDBBLACK, COLOR_RED, COLOR_BLACK);
//init_pair(FGREENBBLACK, COLOR_GREEN, COLOR_BLACK);
//init_pair(FYELLOWBBLACK, COLOR_YELLOW, COLOR_BLACK);
//init_pair(FBLUEBBLACK, COLOR_BLUE, COLOR_BLACK);
//init_pair(FMAGENTABBLACK, COLOR_MAGENTA, COLOR_BLACK);
//init_pair(FCYANBBLACK, COLOR_CYAN, COLOR_BLACK);

#endif
